# permissions for end users to edit autoscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: autoscaling-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: telemetry-operator
    app.kubernetes.io/part-of: telemetry-operator
    app.kubernetes.io/managed-by: kustomize
  name: autoscaling-editor-role
rules:
- apiGroups:
  - telemetry.openstack.org
  resources:
  - autoscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - autoscalings/status
  verbs:
  - get
