# permissions for end users to edit ceilometers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceilometer-editor-role
rules:
- apiGroups:
  - telemetry.openstack.org
  resources:
  - ceilometers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - ceilometers/status
  verbs:
  - get
