apiVersion: telemetry.openstack.org/v1beta1
kind: Telemetry
metadata:
  name: telemetry
spec:
  metricStorage:
    enabled: false
    monitoringStack:
      alertingEnabled: true
      scrapeInterval: 30s
      storage:
        strategy: persistent
        retention: 24h
        persistent:
          pvcStorageRequest: 20G
    prometheusTls:
      caBundleSecretName: combined-ca-bundle
      secretName: cert-metric-storage-prometheus-svc
  autoscaling:
    enabled: false
    aodh:
      passwordSelectors:
      databaseUser: aodh
      databaseInstance: openstack
      memcachedInstance: memcached
      secret: osp-secret
      tls:
        api:
          internal:
            secretName: cert-aodh-internal-svc
          public:
            secretName: cert-aodh-public-svc
        caBundleSecretName: combined-ca-bundle
    heatInstance: heat
  ceilometer:
    enabled: true
    secret: osp-secret
    tls:
      caBundleSecretName: combined-ca-bundle
      secretName: cert-ceilometer-internal-svc
  logging:
    enabled: false
    port: 10514
